### ISSUE TITLE
룸 인포 출력 너저분

### ISSUE THREAD

**Issue by wooyebin** [wooyebin/sysprgm_2team#30]
https://github.com/wooyebin/sysprgm_2team/blob/261f29413d00ff5f1520b12c10328346df88069b/client.c#L235

**Comment by DongHyeonHDH** [comment]
for(int i = 0; i < 10; i++){
	    str_len = read(sock, (void*)&sendinfo, sizeof(sendinfo));
	    if(sendinfo.cnt > 0){
	        printf("RoomName : %s cnt: %d/10 RoomNumber : %d ", sendinfo.roomName, sendinfo.cnt, sendinfo.roomnum);
        printf("who : ");
	    for(int j=0; j < sendinfo.cnt; j++){
		    printf(" %s", sendinfo.clnt_names[j]);            
            if(j == sendinfo.cnt - 1){
                printf("\n");
            }
            else{
                printf(",");
            }
	    }
	    printf("\n");
	    }
    }

**Comment by wooyebin** [comment]
해결
