### ISSUE TITLE
참고자료) 자료 요약

### ISSUE THREAD

**Issue by wooyebin** [wooyebin/sysprgm_2team#8]
### [영타연습](https://url.kr/j57u1f) & [산성비](https://github.com/parkseulkee/typing_game)
> 파일입출력, 타이머, 쓰레드, 화면처리
### [리듬게임](https://blog.naver.com/demonic3540/221216354889)
> 화면처리
### [클라우드](https://m.blog.naver.com/sooftware/221595830805)
> 파일입출력, 디렉토리, ls, fork, 소켓
### [1:N 파일전송](https://maincodes.tistory.com/m/82)
> 소켓, 쓰레드, 파일입출력
### [채팅](https://good-coding.tistory.com/17)
> 소켓, 쓰레드
### [USB 자료 초기화](https://phaphaya.tistory.com/27)
> dev, 파일입출력, 디렉토리
***
부족한 부분 있으면 코멘트 남겨주세요!!

**[updated** 2021/11/10 22:30]
### [테트리스](https://m.blog.naver.com/azure0777/220295388741)

**Comment by kimmss00** [comment]
채팅같은 경우 서버를 열어두고 사용자가 접속할 때 닉네임정도만 입력한 뒤 서버에 접속하고, 채팅방에 입장했을때 <닉네임>님이 입장하셨습니다. 라는 말이 나오도록 구현한 뒤 서버안에서 유저들이 채팅할 수 있는 기능을 구현하는데 초점을 맞췄습니다.
